services:
  postgres-service:
      image: "postgres:latest"
      container_name: "postgres"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
      ports:
        - "5432:5432"

  pgadmin-service:
    image: "dpage/pgadmin4"
    container_name: "pgadmin2"
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@test.com
      - PGADMIN_DEFAULT_PASSWORD=test
    ports:
      - "82:80"

  backend:
    build: .
    container_name: backend
    image: backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres-service


