name: docker-build-and-push

on:
  push:
    branches:
      - 'kubernetes'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        run: |
          docker build -t kixer/backend ./backend
          docker push kixer/backend
  deploy:
        needs: build
        runs-on:
            - self-hosted
            - label-1
        steps:
            - uses: actions/checkout@v2
            
            - name: Run scripts
              run: |
                cd ../CICD-Project
                git pull
                git checkout kubernetes
                cd CICD-Project/kubernetes/
                helm upgrade --install postgres-chart postgres
                helm upgrade --install backend-chart backend
                kubectl rollout restart deployment backenddeployment
